spring.application.name=payment-wallet-system
server.port=8080
spring.sql.init.mode=never
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

app.datasource.control.url=jdbc:h2:file:./data/control-db;MODE=PostgreSQL;DB_CLOSE_DELAY=-1
app.datasource.control.username=sa
app.datasource.control.password=

app.datasource.paytm.url=jdbc:h2:file:./data/paytm-db;MODE=PostgreSQL;DB_CLOSE_DELAY=-1
app.datasource.paytm.username=sa
app.datasource.paytm.password=

app.datasource.uber.url=jdbc:h2:file:./data/uber-db;MODE=PostgreSQL;DB_CLOSE_DELAY=-1
app.datasource.uber.username=sa
app.datasource.uber.password=

logging.level.root=INFO
logging.level.org.springframework=INFO
logging.level.org.springframework.jdbc.core=INFO
