drop table if exists transfer_steps;
drop table if exists transfer_requests;

create table transfer_requests (
    transfer_id varchar(64) primary key,
    mode varchar(40) not null,
    from_wallet varchar(64) not null,
    to_wallet varchar(64) not null,
    amount decimal(19, 2) not null,
    currency varchar(10) not null,
    note varchar(255),
    status varchar(40) not null,
    failure_reason varchar(255),
    simulate_credit_failure boolean not null default false,
    created_at timestamp not null,
    updated_at timestamp not null
);

create table transfer_steps (
    id bigint generated by default as identity primary key,
    transfer_id varchar(64) not null,
    step_order int not null,
    step_name varchar(80) not null,
    step_status varchar(40) not null,
    message varchar(255),
    created_at timestamp not null
);
