drop table if exists wallet_ledger;
drop table if exists wallet_holds;
drop table if exists wallet_accounts;

create table wallet_accounts (
    wallet_id varchar(64) primary key,
    owner_name varchar(120) not null,
    wallet_type varchar(40) not null,
    currency varchar(10) not null,
    balance decimal(19, 2) not null,
    locked_amount decimal(19, 2) not null default 0,
    status varchar(20) not null,
    updated_at timestamp not null
);

create table wallet_holds (
    hold_id bigint generated by default as identity primary key,
    transfer_id varchar(64) not null unique,
    wallet_id varchar(64) not null,
    amount decimal(19, 2) not null,
    hold_type varchar(20) not null,
    status varchar(20) not null,
    note varchar(255),
    created_at timestamp not null,
    updated_at timestamp not null
);

create table wallet_ledger (
    entry_id bigint generated by default as identity primary key,
    transfer_id varchar(64) not null,
    wallet_id varchar(64) not null,
    entry_type varchar(40) not null,
    amount decimal(19, 2) not null,
    balance_after decimal(19, 2) not null,
    note varchar(255),
    created_at timestamp not null
);
